### ISSUE TITLE
ML Algorithms from Scratch

### ISSUE THREAD

**Issue by divyanshugit** [divyanshugit/Avid-Algorithms#13]
Before submitting PR make sure you follow all the steps mentioned in [CONTRIBUTING.md](https://github.com/divyanshugit/Avid-Algorithms/blob/master/CONTRIBUTING.md)

A great way to learn about ML Algorithms is to implement it from scratch. Here are some suggestions:
`k Nearest Neighbour`
`Naive Bayes`
`k Means`
`Decision Tree`

You can implement any Machine Learning algorithms as per your convenience.

This emoji 🚀 is a symbol for the go ahead and submit a PR.
---

**Comment by pvtr-malli** [comment]
is this a part of the hackoctoberfest issue?

**Comment by divyanshugit** [comment]
@pavi-ninjaac Yupp

**Comment by pvtr-malli** [comment]
thank you, then i would like to contribute ...

**Comment by ankitajais20** [comment]
@divyanshugit please assign this to me, i would like to contribute.

**Comment by pvtr-malli** [comment]
@divyanshugit do i need to create a issue for the particular algorithm like ankitajais20  did?

**Comment by divyanshugit** [comment]
@pavi-ninjaac If you want, you can create a issue.

**Comment by pvtr-malli** [comment]
@divyanshugit so that issue assigned for me only?

**Comment by divyanshugit** [comment]
Yupp

**Comment by pvtr-malli** [comment]
@divyanshugit created one for me.....please assign it to me

**Comment by Ankurrsingh** [comment]
> Before submitting PR make sure you follow all the steps mentioned in [CONTRIBUTING.md](https://github.com/divyanshugit/Avid-Algorithms/blob/master/CONTRIBUTING.md)
> 
> A great way to learn about ML Algorithms is to implement it from scratch. Here are some suggestions: `k Nearest Neighbour` `Naive Bayes` `k Means` `Decision Tree`
> 
> You can implement any Machine Learning algorithms as per your convenience.
> 
> ## This emoji 🚀 is a symbol for the go ahead and submit a PR.

Hey I created an issue assign it to me
