### ISSUE TITLE
Leetcode Solution

### ISSUE THREAD

**Issue by divyanshugit** [divyanshugit/Avid-Algorithms#3]
Before submitting PR make sure you follow all the steps mentioned in [CONTRIBUTING.md](https://github.com/divyanshugit/Avid-Algorithms/blob/master/CONTRIBUTING.md)

You can solve any leetcode problem and send a PR in this repo. But you've to maintain the directory structure.
Check out the problems over here: https://leetcode.com/problemset/all/

This emoji 🚀 is a symbol for the go-ahead and submit a PR.
---

**Comment by sourabmaity** [comment]
i want to solve tihs issue

**Comment by CSAURABH** [comment]
@divyanshugit can I work on this issue.

**Comment by DivasGupta7** [comment]
I want to work on this

**Comment by sagar-monga** [comment]
I want to work on this @divyanshugit 
Problem 41. First missing Positive in Java

**Comment by soham4abc** [comment]
Is this Issue open? I would like to work on this

**Comment by TechSpiritSS** [comment]
I would like to add C++ solution for 
https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/

**Comment by noviicee** [comment]
Working on to add a solution for **[Longest Common Subsequence](https://leetcode.com/problems/longest-common-subsequence/)** in **Python**.

**Comment by Masters-Akt** [comment]
I would like to contribute over this

**Comment by ishitaojha** [comment]
Hey, can we contribute in Java too?

**Comment by Shreesh-Kulkarni** [comment]
Hello I would like to contribute by working on the strStr() problem from Leetcode.

**Comment by piyush26arora** [comment]
Hi, I would like to contribute famous n-queens( 1 and 2 ) problem from Leetcode (C++ language).
